/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Appointment {
  date: Date;
  endtime: string;
  id: number;
  starttime: string;
  status: string;
}

export interface Diagnose {
  appt: number;
  diagnosis: string;
  doctor: string;
  prescription: string;
}

export interface DocsHaveSchedules {
  doctor: string;
  sched: number;
}

export interface Doctor {
  address: Generated<string | null>;
  age: Generated<number | null>;
  email: string;
  gender: string;
  name: string;
  password: string;
}

export interface DoctorViewsHistory {
  doctor: string;
  history: number;
}

export interface MedicalHistory {
  conditions: string;
  date: Date;
  id: number;
  medication: string;
  surgeries: string;
}

export interface Medications {
  category: Generated<string | null>;
  description: Generated<string | null>;
  dosage: Generated<string | null>;
  name: string;
  stock: Generated<number | null>;
}

export interface Patient {
  address: string;
  age: Generated<number | null>;
  conditions: Generated<string | null>;
  email: string;
  gender: string;
  height: Generated<string | null>;
  medications: Generated<string | null>;
  name: string;
  password: Generated<string | null>;
  surgeries: Generated<string | null>;
  weight: Generated<string | null>;
}

export interface PatientsAttendAppointments {
  appt: number;
  concerns: string;
  patient: string;
  symptoms: string;
}

export interface PatientsFillHistory {
  history: number;
  patient: string;
}

export interface Schedule {
  breaktime: string;
  day: string;
  endtime: string;
  id: number;
  starttime: string;
}

export interface Users {
  created_at: Generated<Date | null>;
  email: string;
  id: Generated<number>;
  password: string;
  /**
   * 0:病人;1:医生;2:管理
   */
  role: Generated<number>;
  updated_at: Generated<Date | null>;
}

export interface DB {
  Appointment: Appointment;
  Diagnose: Diagnose;
  DocsHaveSchedules: DocsHaveSchedules;
  Doctor: Doctor;
  DoctorViewsHistory: DoctorViewsHistory;
  MedicalHistory: MedicalHistory;
  Medications: Medications;
  Patient: Patient;
  PatientsAttendAppointments: PatientsAttendAppointments;
  PatientsFillHistory: PatientsFillHistory;
  Schedule: Schedule;
  Users: Users;
}
